Traceback (most recent call last):
  File "/Users/tyler/.micromamba/envs/dtl2024/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/tyler/.micromamba/envs/dtl2024/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tyler/.micromamba/envs/dtl2024/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tyler/.micromamba/envs/dtl2024/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/tyler/.micromamba/envs/dtl2024/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/tyler/.micromamba/envs/dtl2024/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/tyler/.micromamba/envs/dtl2024/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
attentions = [attn.squeeze(0).numpy() for attn in outputs.attentions]
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[42], line 1[0m
[0;32m----> 1[0m attentions [38;5;241m=[39m [[43mattn[49m[38;5;241;43m.[39;49m[43msqueeze[49m[43m([49m[38;5;241;43m0[39;49m[43m)[49m[38;5;241;43m.[39;49m[43mnumpy[49m[43m([49m[43m)[49m [38;5;28;01mfor[39;00m attn [38;5;129;01min[39;00m outputs[38;5;241m.[39mattentions]

[0;31mTypeError[0m: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

